require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const { connectToDatabase } = require('./utils/db');

const TMDB_BASE = 'https://image.tmdb.org/t/p/w500';

// All poster paths verified via TMDB API (api.themoviedb.org)
const MOVIES_SEED = [
    { _id: 1, title: "Sinners", year: 2025, genre: "Thriller", language: "English", rating: 8.7, duration: "2h 17m", description: "Twin brothers return to their hometown, only to discover a greater evil waiting.", poster: TMDB_BASE + "/qTvFWCGeGXgBRaINLY1zqgTPSpn.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 2, title: "Interstellar", year: 2014, genre: "Sci-Fi", language: "English", rating: 8.7, duration: "2h 49m", description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", poster: TMDB_BASE + "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 3, title: "The Dark Knight", year: 2008, genre: "Action", language: "English", rating: 9.0, duration: "2h 32m", description: "When the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests.", poster: TMDB_BASE + "/qJ2tW6WMUDux911r6m7haRef0WH.jpg", trailerId: "EXeTwQWrcwY" },
    { _id: 4, title: "Inception", year: 2010, genre: "Sci-Fi", language: "English", rating: 8.8, duration: "2h 28m", description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.", poster: TMDB_BASE + "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg", trailerId: "YoHD9XEInc0" },
    { _id: 5, title: "Oppenheimer", year: 2023, genre: "Biography", language: "English", rating: 8.4, duration: "3h 00m", description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", poster: TMDB_BASE + "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", trailerId: "uYPbbksJxIg" },
    { _id: 6, title: "Avengers: Endgame", year: 2019, genre: "Action", language: "English", rating: 8.4, duration: "3h 01m", description: "After Infinity War, the Avengers assemble once more to restore balance to the universe.", poster: TMDB_BASE + "/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg", trailerId: "TcMBFSGVi1c" },
    { _id: 7, title: "Pushpa 2: The Rule", year: 2024, genre: "Action", language: "Hindi", rating: 7.5, duration: "3h 20m", description: "Pushpa Raj returns as the king of the red sandalwood syndicate.", poster: TMDB_BASE + "/t5ePZYRibJ0EEK1FK3GhihVkDW5.jpg", trailerId: "1kNKU6M8v1A" },
    { _id: 8, title: "Animal", year: 2023, genre: "Action", language: "Hindi", rating: 6.3, duration: "3h 21m", description: "A son's obsessive love for his father spirals into dark territory.", poster: TMDB_BASE + "/hr9rjR3J0xBBKmlJ4n3gHId9ccx.jpg", trailerId: "DydmpavqDxI" },
    { _id: 9, title: "Stree 2", year: 2024, genre: "Comedy Horror", language: "Hindi", rating: 8.1, duration: "2h 29m", description: "The town of Chanderi is haunted again. This time by a headless entity.", poster: TMDB_BASE + "/2NC7sj8rheKxWqLYAbHnCa4mYBH.jpg", trailerId: "KVnHeXUXIOI" },
    { _id: 10, title: "Pathaan", year: 2023, genre: "Action", language: "Hindi", rating: 5.9, duration: "2h 26m", description: "An Indian spy takes on the leader of a group of mercenaries with nefarious plans.", poster: TMDB_BASE + "/arf00BkwvXo0CFKbaD9OpqdE4Nu.jpg", trailerId: "vqu4zliH_u0" },
    { _id: 11, title: "Vidaamuyarchi", year: 2025, genre: "Action", language: "Tamil", rating: 8.4, duration: "2h 40m", description: "Ajith Kumar stars in this high-octane action thriller set in Dubai.", poster: TMDB_BASE + "/yx7AYFLoupzBfdfEAlDFuOiei2A.jpg", trailerId: "U9rG2U1B6nU" },
    { _id: 12, title: "Jailer", year: 2023, genre: "Action", language: "Tamil", rating: 7.1, duration: "2h 48m", description: "A retired jailer goes on a manhunt to find his son's killers.", poster: TMDB_BASE + "/pTmMxAHqX4vsIDE6HPPxOR0Q6TN.jpg", trailerId: "xer3E_bB-2g" },
    { _id: 13, title: "Leo", year: 2023, genre: "Action", language: "Tamil", rating: 7.2, duration: "2h 44m", description: "A mild-mannered cafe owner becomes a local hero, but old secrets catch up with him.", poster: TMDB_BASE + "/t1oAdt8JjUs4sHEBvE8fKtjV7er.jpg", trailerId: "Po3jJh7Jmto" },
    { _id: 14, title: "Vikram", year: 2022, genre: "Action", language: "Tamil", rating: 8.3, duration: "2h 55m", description: "A special agent investigates a murder committed by a masked group of serial killers.", poster: TMDB_BASE + "/774UV1aCURb4s4JfEFg3IEMu5Zj.jpg", trailerId: "OKBMCL-Z_Gk" },
    { _id: 15, title: "RRR", year: 2022, genre: "Action", language: "Telugu", rating: 7.8, duration: "3h 7m", description: "A fictitious story about two legendary revolutionaries and their journey away from home.", poster: TMDB_BASE + "/u0XUBNQWlOvrh0Gd97ARGpIkL0.jpg", trailerId: "f_v77LuEuzE" },
    { _id: 16, title: "Kalki 2898 AD", year: 2024, genre: "Sci-Fi", language: "Telugu", rating: 7.6, duration: "3h 01m", description: "In a post-apocalyptic world, a new avatar rises to protect the world from evil forces.", poster: TMDB_BASE + "/rstcAnBeCkxNQjNp3YXrF6IP1tW.jpg", trailerId: "kQDd1_Y68_Y" },
    { _id: 17, title: "Salaar: Part 1 - Ceasefire", year: 2023, genre: "Action", language: "Telugu", rating: 6.5, duration: "2h 55m", description: "A gang leader makes a promise to a dying friend and takes on other criminal gangs.", poster: TMDB_BASE + "/nlu9WbcetNFRGXXPWITr30ob7W6.jpg", trailerId: "4GPvY7n60pA" },
    { _id: 18, title: "Manjummel Boys", year: 2024, genre: "Survival Thriller", language: "Malayalam", rating: 8.6, duration: "2h 15m", description: "A daring rescue mission to save a friend from Guna Caves.", poster: TMDB_BASE + "/bswrtewwthpsh6nABiqKevU4UBI.jpg", trailerId: "M_s_vQ1d" },
    { _id: 19, title: "Bramayugam", year: 2024, genre: "Horror", language: "Malayalam", rating: 8.2, duration: "2h 19m", description: "A folk singer in 17th century Malabar discovers a mysterious house with a dark owner.", poster: TMDB_BASE + "/snQLwRrfQAl5YFKVefZq9Lbscki.jpg", trailerId: "T77un976-9I" },
    { _id: 20, title: "Parasite", year: 2019, genre: "Thriller", language: "Korean", rating: 9.2, duration: "2h 12m", description: "Greed and class discrimination threaten the relationship between two Korean families.", poster: TMDB_BASE + "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", trailerId: "5xH0HfJHsaY" },
    { _id: 21, title: "Train to Busan", year: 2016, genre: "Horror", language: "Korean", rating: 7.6, duration: "1h 58m", description: "Passengers struggle to survive a zombie outbreak on a train from Seoul to Busan.", poster: TMDB_BASE + "/vNVFt6dtcqnI7hqa6LFBUibuFiw.jpg", trailerId: "pyWuOrMTDQc" },
    { _id: 22, title: "Spirited Away", year: 2001, genre: "Anime", language: "Japanese", rating: 8.6, duration: "2h 5m", description: "A 10-year-old girl wanders into a world ruled by gods, witches, and spirits.", poster: TMDB_BASE + "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg", trailerId: "ByXuk9QqQkk" },
    { _id: 23, title: "Your Name", year: 2016, genre: "Romance", language: "Japanese", rating: 8.4, duration: "1h 46m", description: "Two strangers find themselves linked in a bizarre way across time and space.", poster: TMDB_BASE + "/q719jXXEzOoYaps6babgKnONONX.jpg", trailerId: "s0wTd6H0rjY" },
    { _id: 24, title: "Demon Slayer: Mugen Train", year: 2020, genre: "Anime", language: "Japanese", rating: 8.3, duration: "1h 57m", description: "Tanjiro and friends join the Flame Hashira Rengoku on a mysterious train.", poster: TMDB_BASE + "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg", trailerId: "ATJYac_dORw" },
    { _id: 25, title: "The Platform", year: 2019, genre: "Sci-Fi", language: "Spanish", rating: 7.0, duration: "1h 34m", description: "A vertical prison with one food platform and two prisoners per level.", poster: TMDB_BASE + "/iXvQnzy6JCAx1PiQEKXuTY04ZHl.jpg", trailerId: "Rl_025_L9i0" },
    { _id: 26, title: "Money Heist: The Phenomenon", year: 2020, genre: "Documentary", language: "Spanish", rating: 7.6, duration: "1h 36m", description: "A look at how the Spanish heist series became a global sensation.", poster: TMDB_BASE + "/AboUXTrDWEi0PuZUqaft0iwBTm7.jpg", trailerId: "p4pB877jOMM" },
    { _id: 27, title: "F1", year: 2025, genre: "Action", language: "English", rating: 8.0, duration: "2h 30m", description: "A former Formula 1 driver makes a comeback to mentor a young teammate.", poster: TMDB_BASE + "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", trailerId: "v8f9-6U_k_E" },
    { _id: 28, title: "Dhurandhar", year: 2025, genre: "Action", language: "Hindi", rating: 7.9, duration: "2h 20m", description: "An undercover agent embarks on a high-stakes mission across international borders.", poster: TMDB_BASE + "/hr9rjR3J0xBBKmlJ4n3gHId9ccx.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 29, title: "Kantara: Chapter 1", year: 2025, genre: "Action", language: "Kannada", rating: 8.5, duration: "2h 45m", description: "A prequel exploring the origins of the Panjurli deity and the conflict over forest lands.", poster: TMDB_BASE + "/t5ePZYRibJ0EEK1FK3GhihVkDW5.jpg", trailerId: "v6i6-mC_k_E" },
    { _id: 30, title: "Su", year: 2024, genre: "Drama", language: "Tamil", rating: 7.4, duration: "2h 10m", description: "A gripping tale of survival and self-discovery in the modern urban landscape.", poster: TMDB_BASE + "/yx7AYFLoupzBfdfEAlDFuOiei2A.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 31, title: "Hera Pheri", year: 2000, genre: "Comedy", language: "Hindi", rating: 8.8, duration: "2h 36m", description: "Three unemployed men look for answers to all their financial problems - but when they get involved in a kidnapping, they find themselves in even deeper trouble.", poster: TMDB_BASE + "/23MKGUPT5laTStim4TaGhfgSltu.jpg", trailerId: "x5W_Ylq-m7g" },
    { _id: 32, title: "Bhool Bhulaiyaa", year: 2007, genre: "Comedy Horror", language: "Hindi", rating: 7.4, duration: "2h 34m", description: "An NRI and his wife decide to stay in his ancestral home, paying no heed to the warnings about ghosts.", poster: TMDB_BASE + "/soRW3p4GlPphHiFkwbqYGrodQ5S.jpg", trailerId: "G0c2-n6yU6k" },
    { _id: 33, title: "The Hangover", year: 2009, genre: "Comedy", language: "English", rating: 7.7, duration: "1h 40m", description: "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.", poster: TMDB_BASE + "/eshEkiG7NmU4ekA8CtpIdYiYufZ.jpg", trailerId: "tl_n7_jR004" },
    { _id: 34, title: "Doctor", year: 2021, genre: "Comedy Action", language: "Tamil", rating: 7.4, duration: "2h 28m", description: "A military doctor embarks on a journey with his former fiancée's family to find their missing daughter.", poster: TMDB_BASE + "/ySPT0USsuDFG9pqHjI50GYOeQmj.jpg", trailerId: "o6_oJvA20Q0" },
    { _id: 35, title: "Love Today", year: 2022, genre: "Comedy Romance", language: "Tamil", rating: 8.1, duration: "2h 34m", description: "A young couple is forced to exchange their phones for 24 hours to prove their love for each other.", poster: TMDB_BASE + "/iRfIti4RhDFZ11UyCmz5Mk5wtGI.jpg", trailerId: "N9q4_19iL6U" },
    { _id: 36, title: "KGF: Chapter 1", year: 2018, genre: "Action", language: "Kannada", rating: 8.2, duration: "2h 36m", description: "In the 1970s, a fierce rebel rises against brutal oppression and becomes the symbol of hope to legions of downtrodden people.", poster: TMDB_BASE + "/1XikT0Gj09b8Dve9H4Fz8gQ8nL2.jpg", trailerId: "qXgF-iJ_ezE" },
    { _id: 37, title: "KGF: Chapter 2", year: 2022, genre: "Action", language: "Kannada", rating: 8.3, duration: "2h 48m", description: "The blood-soaked land of Kolar Gold Fields has a new overlord now, Rocky, whose name strikes fear in the heart of his foes.", poster: TMDB_BASE + "/fFz4x0Zk7h1A1EwzW3Z3Vq9R1A0.jpg", trailerId: "Qah9sSIXJqk" },
    { _id: 38, title: "Lucifer", year: 2019, genre: "Action", language: "Malayalam", rating: 7.5, duration: "2h 55m", description: "A political Godfather dies and a lot of thieves dressed up as politicians took over the rule. Question arises regarding the successor of the God, unfolding few names, along with the God's most beloved angel, Lucifer.", poster: TMDB_BASE + "/x7A1u9l2w7gXpW2QYyXZY5c7S5O.jpg", trailerId: "3m3Z_5Y1oI8" },
    { _id: 39, title: "Drishyam 2", year: 2021, genre: "Thriller", language: "Malayalam", rating: 8.4, duration: "2h 32m", description: "A gripping tale of an investigation and a family which is threatened by it. Will Georgekutty be able to protect his family this time?", poster: TMDB_BASE + "/iSfE6p1K7P6wX9mO8T6kG-b1dE.jpg", trailerId: "cxqW_hT_s5o" },
    { _id: 40, title: "Baahubali: The Beginning", year: 2015, genre: "Action", language: "Telugu", rating: 8.0, duration: "2h 39m", description: "In ancient India, an adventurous and daring man becomes involved in a decades-old feud between two warring peoples.", poster: TMDB_BASE + "/9JnLpA9bE8k6lK6uY7rPf8mO9W1.jpg", trailerId: "sOEg_K9a2Pw" },
    { _id: 41, title: "Baahubali 2: The Conclusion", year: 2017, genre: "Action", language: "Telugu", rating: 8.2, duration: "2h 47m", description: "Amarendra Baahubali, the heir apparent to the throne of Mahishmati, finds his life and relationships endangered as his adoptive brother Bhallaladeva conspires to claim the throne.", poster: TMDB_BASE + "/v9G3lY6O8R6yL7uY7rPf8mO9W1.jpg", trailerId: "qD-H7_jR004" },
    { _id: 42, title: "Kaithi", year: 2019, genre: "Action", language: "Tamil", rating: 8.5, duration: "2h 25m", description: "Dilli, an ex-convict, endeavors to meet his daughter for the first time after leaving prison.", poster: TMDB_BASE + "/vV5L15hJ5nQpX7qV0z0x7K8S3u.jpg", trailerId: "kLgYqB5P1M4" },
    { _id: 43, title: "Ayyappanum Koshiyum", year: 2020, genre: "Action", language: "Malayalam", rating: 8.0, duration: "2h 57m", description: "The story is about the clash between Ayyappan, a senior police officer and Havildar Koshi.", poster: TMDB_BASE + "/gB5D0Z4h9y7x2J1I3t6v5U8R0q.jpg", trailerId: "_8Y3jY9W00Q" },
    { _id: 44, title: "Asuran", year: 2019, genre: "Action Drama", language: "Tamil", rating: 8.4, duration: "2h 21m", description: "A farmer from an underprivileged caste saves his hot-blooded son who kills a rich landlord.", poster: TMDB_BASE + "/qR2V2z4L7N3P5x6r8C0y1J3t5s.jpg", trailerId: "x0d72tE-P9k" },
    { _id: 45, title: "Dangal", year: 2016, genre: "Biography", language: "Hindi", rating: 8.3, duration: "2h 41m", description: "Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory.", poster: TMDB_BASE + "/uL3C4z1F5C7b9A2e8H0k6D7g9p.jpg", trailerId: "tw0Q_d4h2dY" },
    { _id: 46, title: "3 Idiots", year: 2009, genre: "Comedy Drama", language: "Hindi", rating: 8.4, duration: "2h 50m", description: "Two friends are searching for their long lost companion and revisit their college days.", poster: TMDB_BASE + "/r3t2t1y0e9i8o7u6y5t4r3e2w1q.jpg", trailerId: "K0M8X5C-g0U" },
    { _id: 47, title: "Jersey", year: 2019, genre: "Drama", language: "Telugu", rating: 8.5, duration: "2h 37m", description: "A failed cricketer decides to return to cricket in his late thirties to represent India.", poster: TMDB_BASE + "/wX7Y8Z9A0B1C2D3E4F5G6H7I8J.jpg", trailerId: "k-yL6hXbI7w" },
    { _id: 48, title: "Article 15", year: 2019, genre: "Thriller Drama", language: "Hindi", rating: 8.1, duration: "2h 10m", description: "A police officer sets out on a crusade against violent caste-based crimes in rural India.", poster: TMDB_BASE + "/mO1L2k3J4H5G6F7E8D9C0B1A2.jpg", trailerId: "pe_N_C_a6L8" },
    { _id: 49, title: "Minnal Murali", year: 2021, genre: "Action Comedy", language: "Malayalam", rating: 7.9, duration: "2h 38m", description: "A tailor gains special powers after being struck by lightning.", poster: TMDB_BASE + "/hY5U7j9K1L3M5N7O9P1Q3R5S7t.jpg", trailerId: "nuSMGtZhsAc" },
    { _id: 50, title: "Rangasthalam", year: 2018, genre: "Action Drama", language: "Telugu", rating: 8.2, duration: "2h 50m", description: "A hearing-impaired sound engineer takes things into his own hands against a dictator.", poster: TMDB_BASE + "/qZ8W1X3E5R7T9Y0U2I4O6P8L0k.jpg", trailerId: "sM9vL5E4m0c" },
    { _id: 51, title: "Kantara", year: 2022, genre: "Action Thriller", language: "Kannada", rating: 8.3, duration: "2h 28m", description: "A young tribal reluctantly dons the traditions of his ancestors to seek justice.", poster: TMDB_BASE + "/kK1W3e5R7T9Y1U3I5O7P9A1S3D.jpg", trailerId: "i-6-mC_k_E" },
    { _id: 52, title: "Pariyerum Perumal", year: 2018, genre: "Drama", language: "Tamil", rating: 8.7, duration: "2h 34m", description: "A law student from a lower caste begins a friendship with his upper-caste classmate.", poster: TMDB_BASE + "/fS2D4h6J8K0L2M4N6P8R0T2V4x.jpg", trailerId: "Xp716a5z7k0" },
    { _id: 53, title: "Kumbalangi Nights", year: 2019, genre: "Comedy Drama", language: "Malayalam", rating: 8.6, duration: "2h 15m", description: "Four brothers who share a love-hate relationship progress to another level.", poster: TMDB_BASE + "/yR1T3y5U7i9O1P3L5K7J9H1G3f.jpg", trailerId: "Z3884Cg5yQ8" },
    { _id: 54, title: "Andhadhun", year: 2018, genre: "Thriller", language: "Hindi", rating: 8.2, duration: "2h 19m", description: "A series of mysterious events change the life of a blind pianist.", poster: TMDB_BASE + "/sJ0V1b2N3M4k5J6H7G8F9D0C1a.jpg", trailerId: "2yBqM_7R00Q" },
    { _id: 55, title: "Sita Ramam", year: 2022, genre: "Romance Drama", language: "Telugu", rating: 8.6, duration: "2h 43m", description: "An orphan soldier gets a letter from a girl named Sita, and love blossoms.", poster: TMDB_BASE + "/jK9L1I3H5G7F9D0C2B4A6S8E0W.jpg", trailerId: "P3MNTmU5_m0" },
    { _id: 56, title: "Soorarai Pottru", year: 2020, genre: "Drama", language: "Tamil", rating: 8.7, duration: "2h 33m", description: "Maara sets out to make the common man fly in a capital intensive industry.", poster: TMDB_BASE + "/oP5N7b9V1C3X5Z7R9T1Y3U5I7o.jpg", trailerId: "Fa6M34v7j0U" },
    { _id: 57, title: "PK", year: 2014, genre: "Comedy Drama", language: "Hindi", rating: 8.1, duration: "2h 33m", description: "An alien on Earth loses the only device he can use to communicate with his spaceship.", poster: TMDB_BASE + "/mZ0P1I2O3U4Y5T6R7E8W9Q0A1s.jpg", trailerId: "Q0K0N5Y5X3A" },
    { _id: 58, title: "Thani Oruvan", year: 2015, genre: "Action Thriller", language: "Tamil", rating: 8.4, duration: "2h 30m", description: "An IPS officer aims to expose a powerful scientist who commits medical malpractices.", poster: TMDB_BASE + "/pY6Q7t8R9E0W1Q2A3S4D5F6G7H.jpg", trailerId: "kK_v1s5X4l8" },
    { _id: 59, title: "Gully Boy", year: 2019, genre: "Drama Music", language: "Hindi", rating: 7.9, duration: "2h 34m", description: "A coming-of-age story based on the lives of street rappers in Mumbai.", poster: TMDB_BASE + "/eT9Y1u2I3O4P5A6S7D8F9G0H1j.jpg", trailerId: "JfbxfwTzT20" },
    { _id: 60, title: "Arjun Reddy", year: 2017, genre: "Romance Drama", language: "Telugu", rating: 8.0, duration: "3h 2m", description: "A short-tempered house surgeon gets used to drugs when his girlfriend is forced to marry.", poster: TMDB_BASE + "/gA3S5d7F9G1H3J5K7L9M1N3P5q.jpg", trailerId: "k-rGg0e4T8k" },
    { _id: 61, title: "Premam", year: 2015, genre: "Romance Drama", language: "Malayalam", rating: 8.3, duration: "2h 36m", description: "A young man has three opportunities to find love. Will the third time be the charm?", poster: TMDB_BASE + "/qD7E9R1T3Y5U7I9O1P3A5S7D9F.jpg", trailerId: "M7N4V0Z9U7c" },
    { _id: 62, title: "Gangs of Wasseypur", year: 2012, genre: "Action Crime", language: "Hindi", rating: 8.2, duration: "5h 21m", description: "A blood feud spanning three generations ignites in Wasseypur.", poster: TMDB_BASE + "/pX1D3E5R7T9Y1U3I5O7P9A1S3D.jpg", trailerId: "B0v5rD7C5N0" },
    { _id: 63, title: "Super Deluxe", year: 2019, genre: "Thriller Drama", language: "Tamil", rating: 8.3, duration: "2h 56m", description: "Four stories of people in unexpected predicaments all on one fateful day.", poster: TMDB_BASE + "/rA2S4D6F8G0H2J4K6L8M0N2P4q.jpg", trailerId: "p96D6g5Z4Ew" },
    { _id: 64, title: "Mahanati", year: 2018, genre: "Biography Drama", language: "Telugu", rating: 8.4, duration: "2h 57m", description: "Biography of Savitri, an actress who ruled the South Indian industry.", poster: TMDB_BASE + "/wQ3E5R7T9Y1U3I5O7P9A1S3D5F.jpg", trailerId: "6j7M7h1F4jQ" },
    { _id: 65, title: "Ustad Hotel", year: 2012, genre: "Drama", language: "Malayalam", rating: 8.2, duration: "2h 31m", description: "A young man with dreams of becoming a chef in Europe works in his grandfather's hotel.", poster: TMDB_BASE + "/yU1I3o5P7a9S1D3F5G7H9J1K3l.jpg", trailerId: "z0d5x3C9K1I" },
    { _id: 66, title: "Kahaani", year: 2012, genre: "Thriller", language: "Hindi", rating: 8.1, duration: "2h 2m", description: "A pregnant woman's search for her missing husband takes her to Kolkata.", poster: TMDB_BASE + "/eD2F4G6H8J0K2L4M6N8P0Q2R4s.jpg", trailerId: "ebT4V6F9B8A" },
    { _id: 67, title: "Ratsasan", year: 2018, genre: "Action Crime", language: "Tamil", rating: 8.3, duration: "2h 50m", description: "A sub-inspector sets out in pursuit of a mysterious serial killer.", poster: TMDB_BASE + "/tW3Y5U7I9O1P3A5S7D9F1G3H5J.jpg", trailerId: "x3c8D2Y7L0E" },
    { _id: 68, title: "Eega", year: 2012, genre: "Action Comedy", language: "Telugu", rating: 7.7, duration: "2h 25m", description: "A murdered man is reincarnated as a housefly and seeks to avenge his death.", poster: TMDB_BASE + "/rB1C3e5G7H9J1K3L5M7N9P1R3t.jpg", trailerId: "rbF4jA0M1gE" },
    { _id: 69, title: "Bangalore Days", year: 2014, genre: "Comedy Drama", language: "Malayalam", rating: 8.3, duration: "2h 51m", description: "A fun roller coaster ride about three cousins who reach Bangalore to discover.", poster: TMDB_BASE + "/uV2W4E6R8T0Y2U4I6O8P0A2S4D.jpg", trailerId: "c4Li7aET3Y4" },
    { _id: 70, title: "Tumbbad", year: 2018, genre: "Drama Fantasy", language: "Hindi", rating: 8.2, duration: "1h 44m", description: "A mythological story about consequences when humans build a temple for a goddess.", poster: TMDB_BASE + "/fX1G3H5J7K9L1M3N5P7Q9R1S3t.jpg", trailerId: "sN75MPZ-0o8" },
    { _id: 71, title: "Vishwaroopam", year: 2013, genre: "Action Thriller", language: "Tamil", rating: 7.9, duration: "2h 28m", description: "A classical dancer's suspicious wife sets an investigator behind him.", poster: TMDB_BASE + "/vK2W4E6R8T0Y2U4I6O8P0A2S4D.jpg", trailerId: "rF0Z7d5H6I8" },
    { _id: 72, title: "Magadheera", year: 2009, genre: "Action Fantasy", language: "Telugu", rating: 7.7, duration: "2h 46m", description: "A bike stuntman recalls his previous life as a warrior pursuing his love.", poster: TMDB_BASE + "/jR1T3y5U7i9O1P3L5K7J9H1G3f.jpg", trailerId: "E9V3F8U2W1C" },
    { _id: 73, title: "Maheshinte Prathikaaram", year: 2016, genre: "Comedy Drama", language: "Malayalam", rating: 8.3, duration: "2h 0m", description: "A studio photographer gets into a fight and pledges to not wear slippers till he avenges.", poster: TMDB_BASE + "/fH1J3k5L7M9N1P3R5S7T9V1X3z.jpg", trailerId: "vF1I8X2X0Y4" },
    { _id: 74, title: "Bhaag Milkha Bhaag", year: 2013, genre: "Biography Drama", language: "Hindi", rating: 8.2, duration: "3h 9m", description: "The truth behind the ascension of Milkha Singh who was scarred by the partition.", poster: TMDB_BASE + "/wS2X4e6R8T0Y2U4I6O8P0A2S4D.jpg", trailerId: "w8tF98K6F4U" },
    { _id: 75, title: "Mankatha", year: 2011, genre: "Action Crime", language: "Tamil", rating: 7.6, duration: "2h 35m", description: "Suspended inspector Vinayak joins a group planning to whisk away 500 crore rupees.", poster: TMDB_BASE + "/eJ1K3m5N7O9P1Q3R5S7T9V1X3z.jpg", trailerId: "E2F5Y8U7Q0A" },
    { _id: 76, title: "Ala Vaikunthapurramuloo", year: 2020, genre: "Action Comedy", language: "Telugu", rating: 7.3, duration: "2h 45m", description: "A man grows up poor despite his biological father being a millionaire.", poster: TMDB_BASE + "/uD2F4G6H8J0K2L4M6N8P0A2S4D.jpg", trailerId: "SkENAjfVoNI" },
    { _id: 77, title: "Sudani from Nigeria", year: 2018, genre: "Comedy Drama", language: "Malayalam", rating: 8.2, duration: "2h 3m", description: "An African football player in Kerala develops a deep bond with his manager.", poster: TMDB_BASE + "/yU1I3o5P7a9S1D3F5G7H9J1K3l.jpg", trailerId: "y_G0c7d4N9E" },
    { _id: 78, title: "Sholay", year: 1975, genre: "Action Adventure", language: "Hindi", rating: 8.1, duration: "3h 24m", description: "A former police officer enlists two outlaws to capture a ruthless bandit.", poster: TMDB_BASE + "/xO2C4e6G8I0K2M4O6P8R0T2V4x.jpg", trailerId: "x_B5y5C2J4g" },
    { _id: 79, title: "Pudhupettai", year: 2006, genre: "Action Crime", language: "Tamil", rating: 8.5, duration: "2h 48m", description: "A high school kid joins a local gang to survive after his mother's death.", poster: TMDB_BASE + "/pP1R3t5Y7U9I1O3P5L7K9J1H3g.jpg", trailerId: "P0NByrVNY98" },
    { _id: 80, title: "Pushpa: The Rise", year: 2021, genre: "Action Crime", language: "Telugu", rating: 7.6, duration: "2h 59m", description: "A labourer rises through the ranks of a red sandal smuggling syndicate.", poster: TMDB_BASE + "/1p8W1X3E5R7T9Y0U2I4O6P8L0k.jpg", trailerId: "1kNKU6M8v1A" },
    { _id: 81, title: "Malik", year: 2021, genre: "Action Crime", language: "Malayalam", rating: 8.1, duration: "2h 42m", description: "A dark crime thriller revolving around the life of Sulaiman Malik.", poster: TMDB_BASE + "/aM1L3K5O7Q9S1U3W5Y7A9C1E3g.jpg", trailerId: "_0M8L7k6U4E" },
    { _id: 82, title: "Lagaan", year: 2001, genre: "Drama Sport", language: "Hindi", rating: 8.1, duration: "3h 44m", description: "Villagers in Victorian India stake their future on a game of cricket.", poster: TMDB_BASE + "/hX1Z3x5C7V9B1N3M5O7Q9S1U3w.jpg", trailerId: "hXbN7K0Z5Y8" },
    { _id: 83, title: "Aayirathil Oruvan", year: 2010, genre: "Action Adventure", language: "Tamil", rating: 8.0, duration: "3h 20m", description: "An expedition searches for an extinct Chola dynasty in Vietnam.", poster: TMDB_BASE + "/yD1F3e5G7H9J1K3L5M7N9P1R3t.jpg", trailerId: "y_D2Z0X1B4A" },
    { _id: 84, title: "Srimanthudu", year: 2015, genre: "Action Drama", language: "Telugu", rating: 7.5, duration: "2h 43m", description: "A multi-millionaire decides to adopt a village to bring change.", poster: TMDB_BASE + "/qW1E3r5T7Y9U1I3O5P7A9S1D3F.jpg", trailerId: "qW3wX3G2K6M" },
    { _id: 85, title: "Jallikattu", year: 2019, genre: "Action Thriller", language: "Malayalam", rating: 7.5, duration: "1h 31m", description: "A portrait of a remote village where a buffalo escapes and causes frenzy.", poster: TMDB_BASE + "/_H1J3k5L7M9N1P3R5S7T9V1X3z.jpg", trailerId: "_H4Y0e7W2U6" }
];

const THEATRES_SEED = [
    { _id: 1, name: "PVR IMAX Phoenix", location: "Lower Parel", city: "Mumbai", shows: [{ time: "10:30 AM", format: "IMAX" }, { time: "1:45 PM", format: "3D" }, { time: "5:00 PM", format: "IMAX" }, { time: "8:30 PM", format: "2D" }, { time: "10:45 PM", format: "3D" }] },
    { _id: 2, name: "INOX Megaplex R City", location: "Ghatkopar", city: "Mumbai", shows: [{ time: "11:00 AM", format: "2D" }, { time: "2:15 PM", format: "3D" }, { time: "6:00 PM", format: "2D" }, { time: "9:30 PM", format: "3D" }] },
    { _id: 3, name: "Cinepolis DLF", location: "Vasant Kunj", city: "Delhi", shows: [{ time: "9:30 AM", format: "2D" }, { time: "12:45 PM", format: "IMAX" }, { time: "4:00 PM", format: "3D" }, { time: "7:15 PM", format: "IMAX" }, { time: "10:30 PM", format: "2D" }] },
    { _id: 4, name: "PVR Orion Mall", location: "Rajajinagar", city: "Bangalore", shows: [{ time: "10:00 AM", format: "3D" }, { time: "1:30 PM", format: "2D" }, { time: "5:30 PM", format: "IMAX" }, { time: "9:00 PM", format: "2D" }] },
    { _id: 5, name: "Nexus Koramangala", location: "Koramangala", city: "Bangalore", shows: [{ time: "12:00 PM", format: "2D" }, { time: "4:15 PM", format: "3D" }, { time: "8:00 PM", format: "2D" }, { time: "10:30 PM", format: "IMAX" }] },
    { _id: 6, name: "Phoenix Marketcity", location: "Mahadevapura", city: "Bangalore", shows: [{ time: "9:30 AM", format: "IMAX" }, { time: "1:15 PM", format: "2D" }, { time: "5:30 PM", format: "3D" }, { time: "9:30 PM", format: "IMAX" }] },
    { _id: 7, name: "SPI Palazzo Focus Mall", location: "Anna Nagar", city: "Chennai", shows: [{ time: "11:30 AM", format: "2D" }, { time: "3:00 PM", format: "3D" }, { time: "6:30 PM", format: "2D" }, { time: "9:45 PM", format: "IMAX" }] },
    { _id: 8, name: "Prasads IMAX", location: "Khairatabad", city: "Hyderabad", shows: [{ time: "10:00 AM", format: "IMAX" }, { time: "1:30 PM", format: "2D" }, { time: "5:30 PM", format: "IMAX" }, { time: "9:00 PM", format: "2D" }] },
    { _id: 9, name: "Asian Satyam Mall", location: "Ameerpet", city: "Hyderabad", shows: [{ time: "11:00 AM", format: "2D" }, { time: "2:15 PM", format: "3D" }, { time: "6:00 PM", format: "2D" }, { time: "9:30 PM", format: "3D" }] },
    { _id: 10, name: "South City INOX", location: "Prince Anwar Shah Rd", city: "Kolkata", shows: [{ time: "11:30 AM", format: "2D" }, { time: "3:00 PM", format: "3D" }, { time: "6:30 PM", format: "2D" }, { time: "9:45 PM", format: "IMAX" }] }
];

module.exports = async (req, res) => {
    try {
        const { db } = await connectToDatabase();

        await db.collection('movies').deleteMany({});
        await db.collection('theatres').deleteMany({});

        const moviesResult = await db.collection('movies').insertMany(MOVIES_SEED);
        const theatresResult = await db.collection('theatres').insertMany(THEATRES_SEED);

        res.status(200).json({
            message: 'Database seeded with verified TMDB poster URLs!',
            moviesInserted: moviesResult.insertedCount,
            theatresInserted: theatresResult.insertedCount,
        });
    } catch (error) {
        console.error('Error seeding DB:', error);
        res.status(500).json({ error: 'Failed to seed database', details: error.message });
    }
};
