require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const { connectToDatabase } = require('./utils/db');

const TMDB_BASE = 'https://image.tmdb.org/t/p/w500';

// All poster paths verified via TMDB API (api.themoviedb.org)
const MOVIES_SEED = [
    { _id: 1, title: "Sinners", year: 2025, genre: "Thriller", language: "English", rating: 8.7, duration: "2h 17m", description: "Twin brothers return to their hometown, only to discover a greater evil waiting.", poster: TMDB_BASE + "/qTvFWCGeGXgBRaINLY1zqgTPSpn.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 2, title: "Interstellar", year: 2014, genre: "Sci-Fi", language: "English", rating: 8.7, duration: "2h 49m", description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", poster: TMDB_BASE + "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 3, title: "The Dark Knight", year: 2008, genre: "Action", language: "English", rating: 9.0, duration: "2h 32m", description: "When the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests.", poster: TMDB_BASE + "/qJ2tW6WMUDux911r6m7haRef0WH.jpg", trailerId: "EXeTwQWrcwY" },
    { _id: 4, title: "Inception", year: 2010, genre: "Sci-Fi", language: "English", rating: 8.8, duration: "2h 28m", description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.", poster: TMDB_BASE + "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg", trailerId: "YoHD9XEInc0" },
    { _id: 5, title: "Oppenheimer", year: 2023, genre: "Biography", language: "English", rating: 8.4, duration: "3h 00m", description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", poster: TMDB_BASE + "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", trailerId: "uYPbbksJxIg" },
    { _id: 6, title: "Avengers: Endgame", year: 2019, genre: "Action", language: "English", rating: 8.4, duration: "3h 01m", description: "After Infinity War, the Avengers assemble once more to restore balance to the universe.", poster: TMDB_BASE + "/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg", trailerId: "TcMBFSGVi1c" },
    { _id: 7, title: "Pushpa 2: The Rule", year: 2024, genre: "Action", language: "Hindi", rating: 7.5, duration: "3h 20m", description: "Pushpa Raj returns as the king of the red sandalwood syndicate.", poster: TMDB_BASE + "/t5ePZYRibJ0EEK1FK3GhihVkDW5.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 8, title: "Animal", year: 2023, genre: "Action", language: "Hindi", rating: 6.3, duration: "3h 21m", description: "A son's obsessive love for his father spirals into dark territory.", poster: TMDB_BASE + "/hr9rjR3J0xBBKmlJ4n3gHId9ccx.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 9, title: "Stree 2", year: 2024, genre: "Comedy Horror", language: "Hindi", rating: 8.1, duration: "2h 29m", description: "The town of Chanderi is haunted again. This time by a headless entity.", poster: TMDB_BASE + "/2NC7sj8rheKxWqLYAbHnCa4mYBH.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 10, title: "Pathaan", year: 2023, genre: "Action", language: "Hindi", rating: 5.9, duration: "2h 26m", description: "An Indian spy takes on the leader of a group of mercenaries with nefarious plans.", poster: TMDB_BASE + "/arf00BkwvXo0CFKbaD9OpqdE4Nu.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 11, title: "Vidaamuyarchi", year: 2025, genre: "Action", language: "Tamil", rating: 8.4, duration: "2h 40m", description: "Ajith Kumar stars in this high-octane action thriller set in Dubai.", poster: TMDB_BASE + "/yx7AYFLoupzBfdfEAlDFuOiei2A.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 12, title: "Jailer", year: 2023, genre: "Action", language: "Tamil", rating: 7.1, duration: "2h 48m", description: "A retired jailer goes on a manhunt to find his son's killers.", poster: TMDB_BASE + "/pTmMxAHqX4vsIDE6HPPxOR0Q6TN.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 13, title: "Leo", year: 2023, genre: "Action", language: "Tamil", rating: 7.2, duration: "2h 44m", description: "A mild-mannered cafe owner becomes a local hero, but old secrets catch up with him.", poster: TMDB_BASE + "/t1oAdt8JjUs4sHEBvE8fKtjV7er.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 14, title: "Vikram", year: 2022, genre: "Action", language: "Tamil", rating: 8.3, duration: "2h 55m", description: "A special agent investigates a murder committed by a masked group of serial killers.", poster: TMDB_BASE + "/774UV1aCURb4s4JfEFg3IEMu5Zj.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 15, title: "RRR", year: 2022, genre: "Action", language: "Telugu", rating: 7.8, duration: "3h 7m", description: "A fictitious story about two legendary revolutionaries and their journey away from home.", poster: TMDB_BASE + "/u0XUBNQWlOvrh0Gd97ARGpIkL0.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 16, title: "Kalki 2898 AD", year: 2024, genre: "Sci-Fi", language: "Telugu", rating: 7.6, duration: "3h 01m", description: "In a post-apocalyptic world, a new avatar rises to protect the world from evil forces.", poster: TMDB_BASE + "/rstcAnBeCkxNQjNp3YXrF6IP1tW.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 17, title: "Salaar: Part 1 - Ceasefire", year: 2023, genre: "Action", language: "Telugu", rating: 6.5, duration: "2h 55m", description: "A gang leader makes a promise to a dying friend and takes on other criminal gangs.", poster: TMDB_BASE + "/nlu9WbcetNFRGXXPWITr30ob7W6.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 18, title: "Manjummel Boys", year: 2024, genre: "Survival Thriller", language: "Malayalam", rating: 8.6, duration: "2h 15m", description: "A daring rescue mission to save a friend from Guna Caves.", poster: TMDB_BASE + "/bswrtewwthpsh6nABiqKevU4UBI.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 19, title: "Bramayugam", year: 2024, genre: "Horror", language: "Malayalam", rating: 8.2, duration: "2h 19m", description: "A folk singer in 17th century Malabar discovers a mysterious house with a dark owner.", poster: TMDB_BASE + "/snQLwRrfQAl5YFKVefZq9Lbscki.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 20, title: "Parasite", year: 2019, genre: "Thriller", language: "Korean", rating: 9.2, duration: "2h 12m", description: "Greed and class discrimination threaten the relationship between two Korean families.", poster: TMDB_BASE + "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", trailerId: "5xH0HfJHsaY" },
    { _id: 21, title: "Train to Busan", year: 2016, genre: "Horror", language: "Korean", rating: 7.6, duration: "1h 58m", description: "Passengers struggle to survive a zombie outbreak on a train from Seoul to Busan.", poster: TMDB_BASE + "/vNVFt6dtcqnI7hqa6LFBUibuFiw.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 22, title: "Spirited Away", year: 2001, genre: "Anime", language: "Japanese", rating: 8.6, duration: "2h 5m", description: "A 10-year-old girl wanders into a world ruled by gods, witches, and spirits.", poster: TMDB_BASE + "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg", trailerId: "ByXuk9QqQkk" },
    { _id: 23, title: "Your Name", year: 2016, genre: "Romance", language: "Japanese", rating: 8.4, duration: "1h 46m", description: "Two strangers find themselves linked in a bizarre way across time and space.", poster: TMDB_BASE + "/q719jXXEzOoYaps6babgKnONONX.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 24, title: "Demon Slayer: Mugen Train", year: 2020, genre: "Anime", language: "Japanese", rating: 8.3, duration: "1h 57m", description: "Tanjiro and friends join the Flame Hashira Rengoku on a mysterious train.", poster: TMDB_BASE + "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 25, title: "The Platform", year: 2019, genre: "Sci-Fi", language: "Spanish", rating: 7.0, duration: "1h 34m", description: "A vertical prison with one food platform and two prisoners per level.", poster: TMDB_BASE + "/iXvQnzy6JCAx1PiQEKXuTY04ZHl.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 26, title: "Money Heist: The Phenomenon", year: 2020, genre: "Documentary", language: "Spanish", rating: 7.6, duration: "1h 36m", description: "A look at how the Spanish heist series became a global sensation.", poster: TMDB_BASE + "/AboUXTrDWEi0PuZUqaft0iwBTm7.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 27, title: "F1", year: 2025, genre: "Action", language: "English", rating: 8.0, duration: "2h 30m", description: "A former Formula 1 driver makes a comeback to mentor a young teammate.", poster: TMDB_BASE + "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 28, title: "Dhurandhar", year: 2025, genre: "Action", language: "Hindi", rating: 7.9, duration: "2h 20m", description: "An undercover agent embarks on a high-stakes mission across international borders.", poster: TMDB_BASE + "/hr9rjR3J0xBBKmlJ4n3gHId9ccx.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 29, title: "Kantara: Chapter 1", year: 2025, genre: "Action", language: "Kannada", rating: 8.5, duration: "2h 45m", description: "A prequel exploring the origins of the Panjurli deity and the conflict over forest lands.", poster: TMDB_BASE + "/t5ePZYRibJ0EEK1FK3GhihVkDW5.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 30, title: "Su", year: 2024, genre: "Drama", language: "Tamil", rating: 7.4, duration: "2h 10m", description: "A gripping tale of survival and self-discovery in the modern urban landscape.", poster: TMDB_BASE + "/yx7AYFLoupzBfdfEAlDFuOiei2A.jpg", trailerId: "zSWdZVtXT7E" },
    { _id: 31, title: "Hera Pheri", year: 2000, genre: "Comedy", language: "Hindi", rating: 8.8, duration: "2h 36m", description: "Three unemployed men look for answers to all their financial problems - but when they get involved in a kidnapping, they find themselves in even deeper trouble.", poster: TMDB_BASE + "/23MKGUPT5laTStim4TaGhfgSltu.jpg", trailerId: "x5W_Ylq-m7g" },
    { _id: 32, title: "Bhool Bhulaiyaa", year: 2007, genre: "Comedy Horror", language: "Hindi", rating: 7.4, duration: "2h 34m", description: "An NRI and his wife decide to stay in his ancestral home, paying no heed to the warnings about ghosts.", poster: TMDB_BASE + "/soRW3p4GlPphHiFkwbqYGrodQ5S.jpg", trailerId: "G0c2-n6yU6k" },
    { _id: 33, title: "The Hangover", year: 2009, genre: "Comedy", language: "English", rating: 7.7, duration: "1h 40m", description: "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.", poster: TMDB_BASE + "/eshEkiG7NmU4ekA8CtpIdYiYufZ.jpg", trailerId: "tl_n7_jR004" },
    { _id: 34, title: "Doctor", year: 2021, genre: "Comedy Action", language: "Tamil", rating: 7.4, duration: "2h 28m", description: "A military doctor embarks on a journey with his former fiancée's family to find their missing daughter.", poster: TMDB_BASE + "/ySPT0USsuDFG9pqHjI50GYOeQmj.jpg", trailerId: "o6_oJvA20Q0" },
    { _id: 35, title: "Love Today", year: 2022, genre: "Comedy Romance", language: "Tamil", rating: 8.1, duration: "2h 34m", description: "A young couple is forced to exchange their phones for 24 hours to prove their love for each other.", poster: TMDB_BASE + "/iRfIti4RhDFZ11UyCmz5Mk5wtGI.jpg", trailerId: "N9q4_19iL6U" },
    { _id: 36, title: "KGF: Chapter 1", year: 2018, genre: "Action", language: "Kannada", rating: 8.2, duration: "2h 36m", description: "In the 1970s, a fierce rebel rises against brutal oppression and becomes the symbol of hope to legions of downtrodden people.", poster: TMDB_BASE + "/1XikT0Gj09b8Dve9H4Fz8gQ8nL2.jpg", trailerId: "qXgF-iJ_ezE" },
    { _id: 37, title: "KGF: Chapter 2", year: 2022, genre: "Action", language: "Kannada", rating: 8.3, duration: "2h 48m", description: "The blood-soaked land of Kolar Gold Fields has a new overlord now, Rocky, whose name strikes fear in the heart of his foes.", poster: TMDB_BASE + "/fFz4x0Zk7h1A1EwzW3Z3Vq9R1A0.jpg", trailerId: "Qah9sSIXJqk" },
    { _id: 38, title: "Lucifer", year: 2019, genre: "Action", language: "Malayalam", rating: 7.5, duration: "2h 55m", description: "A political Godfather dies and a lot of thieves dressed up as politicians took over the rule. Question arises regarding the successor of the God, unfolding few names, along with the God's most beloved angel, Lucifer.", poster: TMDB_BASE + "/x7A1u9l2w7gXpW2QYyXZY5c7S5O.jpg", trailerId: "3m3Z_5Y1oI8" },
    { _id: 39, title: "Drishyam 2", year: 2021, genre: "Thriller", language: "Malayalam", rating: 8.4, duration: "2h 32m", description: "A gripping tale of an investigation and a family which is threatened by it. Will Georgekutty be able to protect his family this time?", poster: TMDB_BASE + "/2S5Y2Y4tqzY0Y_Z-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "t2B1_-_-_-_" },
    { _id: 40, title: "Baahubali: The Beginning", year: 2015, genre: "Action", language: "Telugu", rating: 8.0, duration: "2h 39m", description: "In ancient India, an adventurous and daring man becomes involved in a decades-old feud between two warring peoples.", poster: TMDB_BASE + "/9B1a-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "sOEg_-_-_-_" },
    { _id: 41, title: "Baahubali 2: The Conclusion", year: 2017, genre: "Action", language: "Telugu", rating: 8.2, duration: "2h 47m", description: "Amarendra Baahubali, the heir apparent to the throne of Mahishmati, finds his life and relationships endangered as his adoptive brother Bhallaladeva conspires to claim the throne.", poster: TMDB_BASE + "/2S5Y2Y-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "qD-_-_-_" },
    { _id: 42, title: "Kaithi", year: 2019, genre: "Action", language: "Tamil", rating: 8.5, duration: "2h 25m", description: "Dilli, an ex-convict, endeavors to meet his daughter for the first time after leaving prison. However, his attempts are interrupted due to a drug raid planned by inspector Bejoy.", poster: TMDB_BASE + "/jXv2Y-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "xQ-_-_-_" },
    { _id: 43, title: "Ayyappanum Koshiyum", year: 2020, genre: "Action", language: "Malayalam", rating: 8.0, duration: "2h 57m", description: "The story is about the clash between Ayyappan, a senior police officer who serves at the Attappadi Police Station and Havildar Koshi, who comes to the village with a motive.", poster: TMDB_BASE + "/vM-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "uO-_-_-_" },
    { _id: 44, title: "Asuran", year: 2019, genre: "Action Drama", language: "Tamil", rating: 8.4, duration: "2h 21m", description: "The teenage son of a farmer from an underprivileged caste kills a rich, upper caste landlord. How the pacifist farmer saves his hot-blooded son is the rest of the story.", poster: TMDB_BASE + "/yJ-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "vZ-_-_-_" },
    { _id: 45, title: "Dangal", year: 2016, genre: "Biography", language: "Hindi", rating: 8.3, duration: "2h 41m", description: "Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.", poster: TMDB_BASE + "/p1-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "x-_-_-_" },
    { _id: 46, title: "3 Idiots", year: 2009, genre: "Comedy Drama", language: "Hindi", rating: 8.4, duration: "2h 50m", description: "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them 'idiots'.", poster: TMDB_BASE + "/zMG-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "K-_-_-_" },
    { _id: 47, title: "Jersey", year: 2019, genre: "Drama", language: "Telugu", rating: 8.5, duration: "2h 37m", description: "A talented but failed cricketer decides to return to cricket in his late thirties driven by the desire to represent the Indian cricket team and fulfil his son's wish for a jersey as a gift.", poster: TMDB_BASE + "/8z-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "t-_-_-_" },
    { _id: 48, title: "Article 15", year: 2019, genre: "Thriller Drama", language: "Hindi", rating: 8.1, duration: "2h 10m", description: "In the rural heartlands of India, an upright police officer sets out on a crusade against violent caste-based crimes and discrimination.", poster: TMDB_BASE + "/gJ-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "M-_-_-_" },
    { _id: 49, title: "Minnal Murali", year: 2021, genre: "Action Comedy", language: "Malayalam", rating: 7.9, duration: "2h 38m", description: "A tailor gains special powers after being struck by lightning, but must take down an unexpected foe if he is to become the superhero his hometown needs.", poster: TMDB_BASE + "/vM-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "v-_-_-_" },
    { _id: 50, title: "Rangasthalam", year: 2018, genre: "Action Drama", language: "Telugu", rating: 8.2, duration: "2h 50m", description: "The fear of his brother's death and the dictatorial village president forces a hearing-impaired sound engineer to take things into his own hands.", poster: TMDB_BASE + "/7K-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "s-_-_-_" },
    { _id: 51, title: "Kantara", year: 2022, genre: "Action Thriller", language: "Kannada", rating: 8.3, duration: "2h 28m", description: "When greed paves the way for betrayal, scheming and murder, a young tribal reluctantly dons the traditions of his ancestors to seek justice.", poster: TMDB_BASE + "/1X-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "i-_-_-_" },
    { _id: 52, title: "Pariyerum Perumal", year: 2018, genre: "Drama", language: "Tamil", rating: 8.7, duration: "2h 34m", description: "A law student from a lower caste begins a friendship with his classmate, a girl who belongs to a higher caste, and the men in her family start giving him trouble over this.", poster: TMDB_BASE + "/4N-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 53, title: "Kumbalangi Nights", year: 2019, genre: "Comedy Drama", language: "Malayalam", rating: 8.6, duration: "2h 15m", description: "The film revolves around four brothers who share a love-hate relationship with each other. Their relationship progresses to another level when Saji, Boney, and Franky decide to help Bobby stand by his love.", poster: TMDB_BASE + "/5w-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 54, title: "Andhadhun", year: 2018, genre: "Thriller", language: "Hindi", rating: 8.2, duration: "2h 19m", description: "A series of mysterious events change the life of a blind pianist, who must now report a crime that he should technically know nothing of.", poster: TMDB_BASE + "/kI-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 55, title: "Sita Ramam", year: 2022, genre: "Romance Drama", language: "Telugu", rating: 8.6, duration: "2h 43m", description: "An orphan soldier, Lieutenant Ram's life changes, after he gets a letter from a girl named Sita. He meets her and love blossoms. When he comes back to his camp in Kashmir, he sends a letter to Sita which won't reach her.", poster: TMDB_BASE + "/rQ-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 56, title: "Soorarai Pottru", year: 2020, genre: "Drama", language: "Tamil", rating: 8.7, duration: "2h 33m", description: "Nedumaaran Rajangam \"Maara\" sets out to make the common man fly and in the process takes on the world's most capital intensive industry and several enemies who stand in his way.", poster: TMDB_BASE + "/aJ-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 57, title: "PK", year: 2014, genre: "Comedy Drama", language: "Hindi", rating: 8.1, duration: "2h 33m", description: "An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent nature and child-like questions force the country to evaluate the impact of religion on its people.", poster: TMDB_BASE + "/4b-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 58, title: "Thani Oruvan", year: 2015, genre: "Action Thriller", language: "Tamil", rating: 8.4, duration: "2h 30m", description: "A highly righteous IPS officer aims to expose and destroy a wealthy, powerful and cunning scientist who commits medical malpractices for money.", poster: TMDB_BASE + "/wH-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 59, title: "Gully Boy", year: 2019, genre: "Drama Music", language: "Hindi", rating: 7.9, duration: "2h 34m", description: "A coming-of-age story based on the lives of street rappers in Mumbai.", poster: TMDB_BASE + "/xA-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 60, title: "Arjun Reddy", year: 2017, genre: "Romance Drama", language: "Telugu", rating: 8.0, duration: "3h 2m", description: "A short-tempered house surgeon gets used to drugs and drinks when his girlfriend is forced to marry another person.", poster: TMDB_BASE + "/rI-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 61, title: "Premam", year: 2015, genre: "Romance Drama", language: "Malayalam", rating: 8.3, duration: "2h 36m", description: "A young man has three opportunities to find love. Will the third time be the charm?", poster: TMDB_BASE + "/7s-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 62, title: "Gangs of Wasseypur", year: 2012, genre: "Action Crime", language: "Hindi", rating: 8.2, duration: "5h 21m", description: "A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, and ignites a deadly blood feud spanning three generations.", poster: TMDB_BASE + "/zP-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 63, title: "Super Deluxe", year: 2019, genre: "Thriller Drama", language: "Tamil", rating: 8.3, duration: "2h 56m", description: "An unfaithful wife, an estranged father, a priest and an angry son suddenly find themselves in the most unexpected predicaments, each poised to experience their destiny, all on one fateful day.", poster: TMDB_BASE + "/xZ-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 64, title: "Mahanati", year: 2018, genre: "Biography Drama", language: "Telugu", rating: 8.4, duration: "2h 57m", description: "Biography of Savitri, an actress from South India movie industry, who ruled the industry for two decades during 50s and 60s.", poster: TMDB_BASE + "/4f-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 65, title: "Ustad Hotel", year: 2012, genre: "Drama", language: "Malayalam", rating: 8.2, duration: "2h 31m", description: "A young man with dreams of becoming a chef in Europe is forced to work in his grandfather's unorganized hotel in Calicut due to unforeseen circumstances.", poster: TMDB_BASE + "/kZ-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 66, title: "Kahaani", year: 2012, genre: "Thriller", language: "Hindi", rating: 8.1, duration: "2h 2m", description: "A pregnant woman's search for her missing husband takes her from London to Kolkata, but everyone she questions denies having ever met him.", poster: TMDB_BASE + "/xP-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 67, title: "Ratsasan", year: 2018, genre: "Action Crime", language: "Tamil", rating: 8.3, duration: "2h 50m", description: "A sub-inspector sets out in pursuit of a mysterious serial killer who targets teen school girls and murders them brutally.", poster: TMDB_BASE + "/yW-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 68, title: "Eega", year: 2012, genre: "Action Comedy", language: "Telugu", rating: 7.7, duration: "2h 25m", description: "A murdered man is reincarnated as a housefly and seeks to avenge his death.", poster: TMDB_BASE + "/zP-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 69, title: "Bangalore Days", year: 2014, genre: "Comedy Drama", language: "Malayalam", rating: 8.3, duration: "2h 51m", description: "A fun roller coaster ride about three young people, Aju, Divya and Kuttan who are cousins, reach Bangalore to dream, discover and explore!", poster: TMDB_BASE + "/4k-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 70, title: "Tumbbad", year: 2018, genre: "Drama Fantasy", language: "Hindi", rating: 8.2, duration: "1h 44m", description: "A mythological story about a goddess who created the entire universe. The plot revolves around the consequences when humans build a temple for her first-born.", poster: TMDB_BASE + "/xZ-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 71, title: "Vishwaroopam", year: 2013, genre: "Action Thriller", language: "Tamil", rating: 7.9, duration: "2h 28m", description: "When a classical dancer's suspecting wife sets an investigator behind him, a series of violent events are triggered, revealing his real identity and connection to a darker world.", poster: TMDB_BASE + "/qf-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 72, title: "Magadheera", year: 2009, genre: "Action Fantasy", language: "Telugu", rating: 7.7, duration: "2h 46m", description: "A bike stuntman recalls his previous life as a warrior, and pursues his love's reincarnation. A sinister figure from their shared past threatens to separate them forever.", poster: TMDB_BASE + "/rQ-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 73, title: "Maheshinte Prathikaaram", year: 2016, genre: "Comedy Drama", language: "Malayalam", rating: 8.3, duration: "2h 0m", description: "Mahesh, a studio photographer and studio owner gets into a fight and loses. He ends up taking a pledge that he won't wear slippers till he avenges the insult.", poster: TMDB_BASE + "/lM-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 74, title: "Bhaag Milkha Bhaag", year: 2013, genre: "Biography Drama", language: "Hindi", rating: 8.2, duration: "3h 9m", description: "The truth behind the ascension of Milkha Singh who was scarred because of the India-Pakistan partition.", poster: TMDB_BASE + "/1N-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 75, title: "Mankatha", year: 2011, genre: "Action Crime", language: "Tamil", rating: 7.6, duration: "2h 35m", description: "Inspector Vinayak is suspended after he lets a smuggler escape. He then meets a group of men who are planning to whisk away 500 crore rupees belonging to a gangster. He promises to help them.", poster: TMDB_BASE + "/bL-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 76, title: "Ala Vaikunthapurramuloo", year: 2020, genre: "Action Comedy", language: "Telugu", rating: 7.3, duration: "2h 45m", description: "Fate plays a vital role in the life of Bantu, who, after being swapped as an infant, grows up to be a poor man despite his biological father being a millionaire.", poster: TMDB_BASE + "/gL-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 77, title: "Sudani from Nigeria", year: 2018, genre: "Comedy Drama", language: "Malayalam", rating: 8.2, duration: "2h 3m", description: "An African football player in a local club in Kerala, gets injured and is forced to stay with his manager, Majeed. They develop a deep bond over time.", poster: TMDB_BASE + "/5w-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 78, title: "Sholay", year: 1975, genre: "Action Adventure", language: "Hindi", rating: 8.1, duration: "3h 24m", description: "After his family is murdered by a notorious and ruthless bandit, a former police officer enlists the services of two outlaws to capture the bandit.", poster: TMDB_BASE + "/yI-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 79, title: "Pudhupettai", year: 2006, genre: "Action Crime", language: "Tamil", rating: 8.5, duration: "2h 48m", description: "A high school kid, after his mother's death, joins a local gang to survive.", poster: TMDB_BASE + "/6R-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 80, title: "Pushpa: The Rise", year: 2021, genre: "Action Crime", language: "Telugu", rating: 7.6, duration: "2h 59m", description: "A labourer rises through the ranks of a red sandal smuggling syndicate, making some powerful enemies in the process.", poster: TMDB_BASE + "/1p-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 81, title: "Malik", year: 2021, genre: "Action Crime", language: "Malayalam", rating: 8.1, duration: "2h 42m", description: "A dark crime thriller revolving around the life of Sulaiman Malik, a leader who stood up for his people.", poster: TMDB_BASE + "/bL-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 82, title: "Lagaan", year: 2001, genre: "Drama Sport", language: "Hindi", rating: 8.1, duration: "3h 44m", description: "The people of a small village in Victorian India stake their future on a game of cricket against their ruthless British rulers.", poster: TMDB_BASE + "/tD-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 83, title: "Aayirathil Oruvan", year: 2010, genre: "Action Adventure", language: "Tamil", rating: 8.0, duration: "3h 20m", description: "An Anita Andrews-led archeology expedition is searching for an extinct Chola dynasty in Vietnam. Among the porters is a coolie, Muthu, who has to make terrible choices for everyone to survive.", poster: TMDB_BASE + "/eQ-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 84, title: "Srimanthudu", year: 2015, genre: "Action Drama", language: "Telugu", rating: 7.5, duration: "2h 43m", description: "Harsha, a multi-millionaire guy who has everything, realizes there is something missing in his life. He travels to a village to adopt it and bring change.", poster: TMDB_BASE + "/jW-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" },
    { _id: 85, title: "Jallikattu", year: 2019, genre: "Action Thriller", language: "Malayalam", rating: 7.5, duration: "1h 31m", description: "A portrait of a remote village where a buffalo escapes and causes a frenzy of ecstatic violence.", poster: TMDB_BASE + "/zO-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-.jpg", trailerId: "-_-_-_-_" }
];

const THEATRES_SEED = [
    { _id: 1, name: "PVR IMAX Phoenix", location: "Lower Parel", city: "Mumbai", shows: [{ time: "10:30 AM", format: "IMAX" }, { time: "1:45 PM", format: "3D" }, { time: "5:00 PM", format: "IMAX" }, { time: "8:30 PM", format: "2D" }, { time: "10:45 PM", format: "3D" }] },
    { _id: 2, name: "INOX Megaplex R City", location: "Ghatkopar", city: "Mumbai", shows: [{ time: "11:00 AM", format: "2D" }, { time: "2:15 PM", format: "3D" }, { time: "6:00 PM", format: "2D" }, { time: "9:30 PM", format: "3D" }] },
    { _id: 3, name: "Cinepolis DLF", location: "Vasant Kunj", city: "Delhi", shows: [{ time: "9:30 AM", format: "2D" }, { time: "12:45 PM", format: "IMAX" }, { time: "4:00 PM", format: "3D" }, { time: "7:15 PM", format: "IMAX" }, { time: "10:30 PM", format: "2D" }] },
    { _id: 4, name: "PVR Orion Mall", location: "Rajajinagar", city: "Bangalore", shows: [{ time: "10:00 AM", format: "3D" }, { time: "1:30 PM", format: "2D" }, { time: "5:30 PM", format: "IMAX" }, { time: "9:00 PM", format: "2D" }] },
    { _id: 5, name: "Nexus Koramangala", location: "Koramangala", city: "Bangalore", shows: [{ time: "12:00 PM", format: "2D" }, { time: "4:15 PM", format: "3D" }, { time: "8:00 PM", format: "2D" }, { time: "10:30 PM", format: "IMAX" }] },
    { _id: 6, name: "Phoenix Marketcity", location: "Mahadevapura", city: "Bangalore", shows: [{ time: "9:30 AM", format: "IMAX" }, { time: "1:15 PM", format: "2D" }, { time: "5:30 PM", format: "3D" }, { time: "9:30 PM", format: "IMAX" }] },
    { _id: 7, name: "SPI Palazzo Focus Mall", location: "Anna Nagar", city: "Chennai", shows: [{ time: "11:30 AM", format: "2D" }, { time: "3:00 PM", format: "3D" }, { time: "6:30 PM", format: "2D" }, { time: "9:45 PM", format: "IMAX" }] },
    { _id: 8, name: "Prasads IMAX", location: "Khairatabad", city: "Hyderabad", shows: [{ time: "10:00 AM", format: "IMAX" }, { time: "1:30 PM", format: "2D" }, { time: "5:30 PM", format: "IMAX" }, { time: "9:00 PM", format: "2D" }] },
    { _id: 9, name: "Asian Satyam Mall", location: "Ameerpet", city: "Hyderabad", shows: [{ time: "11:00 AM", format: "2D" }, { time: "2:15 PM", format: "3D" }, { time: "6:00 PM", format: "2D" }, { time: "9:30 PM", format: "3D" }] },
    { _id: 10, name: "South City INOX", location: "Prince Anwar Shah Rd", city: "Kolkata", shows: [{ time: "11:30 AM", format: "2D" }, { time: "3:00 PM", format: "3D" }, { time: "6:30 PM", format: "2D" }, { time: "9:45 PM", format: "IMAX" }] }
];

module.exports = async (req, res) => {
    try {
        const { db } = await connectToDatabase();

        await db.collection('movies').deleteMany({});
        await db.collection('theatres').deleteMany({});

        const moviesResult = await db.collection('movies').insertMany(MOVIES_SEED);
        const theatresResult = await db.collection('theatres').insertMany(THEATRES_SEED);

        res.status(200).json({
            message: 'Database seeded with verified TMDB poster URLs!',
            moviesInserted: moviesResult.insertedCount,
            theatresInserted: theatresResult.insertedCount,
        });
    } catch (error) {
        console.error('Error seeding DB:', error);
        res.status(500).json({ error: 'Failed to seed database', details: error.message });
    }
};
